config/routes.rb
Rails.application.routes.draw do
  get          'login'     => 'sessions#new'
  post        'login'     => 'sessions#create'
  delete     'logout'   => 'sessions#destroy'
  get          'signup'   => 'users#new'
  resources :users
  resources :events
  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  include IceCube
  
  validates :start_time, presence: true
  validates :title, presence: true
  validate :start_time_before_end_time

  belongs_to :user
  def start_time_before_end_time
    if self.start_time > self.end_time
      errors.add(:start_time, "Start time should be before end time")
    end
  end
  
  def schedule
      s = Schedule.new(start_time )
      case self.rule
      when 'daily'
        s.add_recurrence_rule Rule.daily
      when 'weekly'
        s.add_recurrence_rule Rule.weekly
      when 'monthly'
        s.add_recurrence_rule Rule.monthly
      when 'yearly'
        s.add_recurrence_rule Rule.yearly
      end
      s
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_many :events

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 	presence: true, length: {maximum: 255 },
  				     	format: { with: VALID_EMAIL_REGEX },
  				     	uniqueness: { case_sensitive: false }
  validates :password_digest, presence: true, length: { minimum: 6}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
    	unless logged_in?
    	  redirect_to login_url
    	end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy, :edit, :update]
  before_action :correct_user, only: [:destroy, :edit, :update]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time, :rule)
    end

    def correct_user
      @event = current_user.events.find_by(id: params[:id])
      redirect_to root_url if @event.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @events = @user.events
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	log_in @user
    	redirect_to @user
    else
    	render 'new'
    end
  end

  def edit
  end

  def update
    
    if @user.update(user_params)
    	redirect_to @user
    else
    	render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
    	@user = current_user
    	redirect_to login_path if @user.nil?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_events.html.erb
<table class="list">
  <thead>
    <tr>
      <th>Title</th>
      <th>Rule</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.rule %></td>
        <td><%= event.user.name %></td>
        <td><%= link_to 'Show', event %></td>
        <% if current_user == event.user %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Event', new_event_path %>
<br>
<br>
<%= month_calendar events: @events do |date, events| %>
  <%= date %>

  <% events.each do |event| %>
    <div>
      <%= link_to event.title, event %>
    </div>
  <% end %>
  <div class="button_add">
    <a href='#' onclick="overlay('<%= date %>')">+</a>
  </div>
<% end %>

<div id="overlay">
  <div>
    Click here to [<a href='#' onclick='overlay()'>close</a>]
    <%= form_tag(controller: "events", action: "create", method: "post") do %>
      <div class="field">
        <%= label_tag "title" %><br>
        <%= text_field :event, :title %>
      </div>
      <div class="field">
        <%= label_tag "description" %><br>
        <%= text_area :event, :description %>
      </div>
      <div class="field">
        <%= label_tag "start_time" %><br>
        <%= text_field :event, :start_time %>
      </div>
      <div class="field">
        <%= label_tag "end_time" %><br>
        <%= text_field :event, :end_time %>
      </div>
      <div class="field">
        <%= label_tag "rule" %><br>
        Empty:<%= radio_button("event", "rule", "empty") %>
        Daily:<%= radio_button("event", "rule", "daily") %>
        Weekly:<%= radio_button("event", "rule", "weekly") %>
        Monthly:<%= radio_button("event", "rule", "monthly") %>
        Yearly:<%= radio_button("event", "rule", "early") %>
      </div>
  
      <div class="field">
        <%= submit_tag "Create" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :rule %><br>
    Empty:<%= radio_button("event", "rule", "empty") %>
    Daily:<%= radio_button("event", "rule", "daily") %>
    Weekly:<%= radio_button("event", "rule", "weekly") %>
    Monthly:<%= radio_button("event", "rule", "monthly") %>
    Yearly:<%= radio_button("event", "rule", "early") %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Events</h1>
<%= render 'events' %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Rule:</strong>
  <%= @event.rule %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user.name %>
</p>
<% if current_user == @event.user %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventcalendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
<div class="logo">
  <%= link_to "EventCalendar", root_url %>
</div>
<ul>
  <% if logged_in? %>
    <li>
    <%= link_to current_user.name, current_user %>
    </li>
    <li>
    <%= link_to "Log out", logout_path, method: "delete" %>
    </li>
  <% else %>
    <li>
    <%= link_to "Log in", login_path %>
    </li>
    <li>
    <%= link_to "Sign up", signup_path %>
    </li>
  <% end %>
  </ul>
</div>

<%= yield %>

</body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", start_date: date_range.first - 1.day  %>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <%= link_to "Next", start_date: date_range.last + 1.day  %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
<div class="control-panel">
  <b><%= link_to "<=", start_date: date_range.first - 1.day  %></b>
  <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  <b><%= link_to "=>", start_date: date_range.last + 1.day  %></b>
</div>


  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <%= link_to "Previous", start_date: date_range.first - 1.day  %>
  Week <%= start_date.strftime("%U").to_i %>
  <%= link_to "Next", start_date: date_range.last + 1.day  %>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= I18n.t("date.abbr_day_names")[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && block_is_haml?(block) %>
                <% capture_haml do %>
                  <% block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
  </div>
  <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
  </div>
  <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br>
      <%= f.password_field :password_confirmation %>
      </div>
  <div class="field">
      <%= f.submit "Create my account", class: "btn btn-primary" %>
  </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if @user == current_user %>
<h3><%= link_to "Edit profile", edit_user_path(@user) %></h3>
<% end %>
<%= render 'events/events' %>